# Generated by Django 5.2.8 on 2026-01-08 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_orderitem_product"),
        ("payments", "0002_alter_payment_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="transaction_id",
            new_name="session_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
